Remove deprecated JQuery event-aliases
Apparently the event aliases like `ready` and `load` were deprecated in JQuery 1.8 and using them gives a `TypeError` on Firefox:

`TypeError: a.indexOf is not a function`

I'm not a JS professional, this is where I learnt about this deprecation from [this StackOverflow question](https://stackoverflow.com/questions/38871753/uncaught-typeerror-a-indexof-is-not-a-function-error-when-opening-new-foundat).